- hosts: localhost
  become: yes
  tasks: 
  - name: Remove transmission packages
    ansible.builtin.apt: pkg={{item}} state=absent
    with_items:
      - transmission
      - transmission-common
      - transmission-gtk
  - name: Install a list of packages
    apt:
      pkg:
        - gcc
        - make
        - perl
        - git
        - gitk
        - curl
        - mc
        - vlc
        - telegram-desktop
        - obs-studio
        - flameshot
        - deluge
        - ncdu
        - remmina
        - virtualbox
        # - virtualbox—ext–pack
        # - pgadmin3 
        # - mysql-workbench
